export const ROUTES = {
  DASHBOARD: '/',
  AUTH: '/auth',
  SETTINGS: '/settings',
  CONTACTS: '/contacts',
  CONTACT_DETAILS: '/contacts/$id',
  NEW_CONTACT: '/contacts/new',
  TRANSACTIONS: '/transactions',
  TRANSACTION_DETAILS: '/transactions/$id',
  NOTIFICATIONS: '/notifications',
  PERSONAL: '/personal',
  PERSONAL_REPORTS: '/personal/reports',
  GROUP_DETAILS: '/groups/$id',
  GROUP_SETTINGS: '/groups/$id/settings',
  GROUP_RECURRING: '/groups/$id/recurring',
  PERSONAL_SETTINGS: '/personal/settings',
  PERSONAL_CATEGORIES: '/personal/categories',
  PERSONAL_HIDE_LEDGERS: '/personal/hide-ledgers',
  PERSONAL_DEFAULT_PERIOD: '/personal/default-period',
  PERSONAL_BUDGET_LIMIT: '/personal/budget-limit',
  PERSONAL_CATEGORY_BUDGETS: '/personal/category-budgets',
  PERSONAL_SET_CATEGORY_LIMIT: '/personal/category-budgets/$catId',
} as const

