export const ROUTES = {
  DASHBOARD: '/',
  AUTH: '/auth',
  SETTINGS: '/settings',
  CONTACTS: '/contacts',
  CONTACT_DETAILS: '/contacts/$id',
  NEW_CONTACT: '/contacts/new',
  TRANSACTIONS: '/transactions',
  TRANSACTION_DETAILS: '/transactions/$id',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  PERSONAL: '/personal',
  PERSONAL_REPORTS: '/personal/reports',
  PERSONAL_ADD: '/personal/add',
  CONTACT_ADD_EXPENSE: '/contacts/$id/add-expense',
  CONTACT_EDIT_EXPENSE: '/contacts/$id/edit-expense',
  CONTACT_REMINDER: '/contacts/$id/reminder',
} as const
