/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as PersonalIndexRouteImport } from './routes/personal/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'
import { Route as PersonalSettingsRouteImport } from './routes/personal/settings'
import { Route as PersonalReportsRouteImport } from './routes/personal/reports'
import { Route as PersonalHideLedgersRouteImport } from './routes/personal/hide-ledgers'
import { Route as PersonalDefaultPeriodRouteImport } from './routes/personal/default-period'
import { Route as PersonalCategoriesRouteImport } from './routes/personal/categories'
import { Route as PersonalBudgetLimitRouteImport } from './routes/personal/budget-limit'
import { Route as GroupsIdRouteImport } from './routes/groups/$id'
import { Route as ContactsNewRouteImport } from './routes/contacts/new'
import { Route as ContactsIdRouteImport } from './routes/contacts/$id'
import { Route as PersonalCategoryBudgetsIndexRouteImport } from './routes/personal/category-budgets.index'
import { Route as GroupsIdIndexRouteImport } from './routes/groups/$id.index'
import { Route as ContactsIdIndexRouteImport } from './routes/contacts/$id.index'
import { Route as PersonalCategoryBudgetsCatIdRouteImport } from './routes/personal/category-budgets.$catId'
import { Route as GroupsIdSettingsRouteImport } from './routes/groups/$id.settings'
import { Route as GroupsIdRecurringRouteImport } from './routes/groups/$id.recurring'
import { Route as GroupsIdRecurringIndexRouteImport } from './routes/groups/$id.recurring.index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalIndexRoute = PersonalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonalRoute,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalSettingsRoute = PersonalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalReportsRoute = PersonalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalHideLedgersRoute = PersonalHideLedgersRouteImport.update({
  id: '/hide-ledgers',
  path: '/hide-ledgers',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalDefaultPeriodRoute = PersonalDefaultPeriodRouteImport.update({
  id: '/default-period',
  path: '/default-period',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalCategoriesRoute = PersonalCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PersonalRoute,
} as any)
const PersonalBudgetLimitRoute = PersonalBudgetLimitRouteImport.update({
  id: '/budget-limit',
  path: '/budget-limit',
  getParentRoute: () => PersonalRoute,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalCategoryBudgetsIndexRoute =
  PersonalCategoryBudgetsIndexRouteImport.update({
    id: '/category-budgets/',
    path: '/category-budgets/',
    getParentRoute: () => PersonalRoute,
  } as any)
const GroupsIdIndexRoute = GroupsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsIdRoute,
} as any)
const ContactsIdIndexRoute = ContactsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsIdRoute,
} as any)
const PersonalCategoryBudgetsCatIdRoute =
  PersonalCategoryBudgetsCatIdRouteImport.update({
    id: '/category-budgets/$catId',
    path: '/category-budgets/$catId',
    getParentRoute: () => PersonalRoute,
  } as any)
const GroupsIdSettingsRoute = GroupsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GroupsIdRoute,
} as any)
const GroupsIdRecurringRoute = GroupsIdRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => GroupsIdRoute,
} as any)
const GroupsIdRecurringIndexRoute = GroupsIdRecurringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsIdRecurringRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/personal': typeof PersonalRouteWithChildren
  '/settings': typeof SettingsRoute
  '/contacts/$id': typeof ContactsIdRouteWithChildren
  '/contacts/new': typeof ContactsNewRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/personal/budget-limit': typeof PersonalBudgetLimitRoute
  '/personal/categories': typeof PersonalCategoriesRoute
  '/personal/default-period': typeof PersonalDefaultPeriodRoute
  '/personal/hide-ledgers': typeof PersonalHideLedgersRoute
  '/personal/reports': typeof PersonalReportsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/auth/': typeof AuthIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/personal/': typeof PersonalIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/groups/$id/recurring': typeof GroupsIdRecurringRouteWithChildren
  '/groups/$id/settings': typeof GroupsIdSettingsRoute
  '/personal/category-budgets/$catId': typeof PersonalCategoryBudgetsCatIdRoute
  '/contacts/$id/': typeof ContactsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/personal/category-budgets/': typeof PersonalCategoryBudgetsIndexRoute
  '/groups/$id/recurring/': typeof GroupsIdRecurringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/contacts/new': typeof ContactsNewRoute
  '/personal/budget-limit': typeof PersonalBudgetLimitRoute
  '/personal/categories': typeof PersonalCategoriesRoute
  '/personal/default-period': typeof PersonalDefaultPeriodRoute
  '/personal/hide-ledgers': typeof PersonalHideLedgersRoute
  '/personal/reports': typeof PersonalReportsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/auth': typeof AuthIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/personal': typeof PersonalIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/groups/$id/settings': typeof GroupsIdSettingsRoute
  '/personal/category-budgets/$catId': typeof PersonalCategoryBudgetsCatIdRoute
  '/contacts/$id': typeof ContactsIdIndexRoute
  '/groups/$id': typeof GroupsIdIndexRoute
  '/personal/category-budgets': typeof PersonalCategoryBudgetsIndexRoute
  '/groups/$id/recurring': typeof GroupsIdRecurringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/personal': typeof PersonalRouteWithChildren
  '/settings': typeof SettingsRoute
  '/contacts/$id': typeof ContactsIdRouteWithChildren
  '/contacts/new': typeof ContactsNewRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/personal/budget-limit': typeof PersonalBudgetLimitRoute
  '/personal/categories': typeof PersonalCategoriesRoute
  '/personal/default-period': typeof PersonalDefaultPeriodRoute
  '/personal/hide-ledgers': typeof PersonalHideLedgersRoute
  '/personal/reports': typeof PersonalReportsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/auth/': typeof AuthIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/personal/': typeof PersonalIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/groups/$id/recurring': typeof GroupsIdRecurringRouteWithChildren
  '/groups/$id/settings': typeof GroupsIdSettingsRoute
  '/personal/category-budgets/$catId': typeof PersonalCategoryBudgetsCatIdRoute
  '/contacts/$id/': typeof ContactsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/personal/category-budgets/': typeof PersonalCategoryBudgetsIndexRoute
  '/groups/$id/recurring/': typeof GroupsIdRecurringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/personal'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/new'
    | '/groups/$id'
    | '/personal/budget-limit'
    | '/personal/categories'
    | '/personal/default-period'
    | '/personal/hide-ledgers'
    | '/personal/reports'
    | '/personal/settings'
    | '/transactions/$id'
    | '/auth/'
    | '/contacts/'
    | '/notifications/'
    | '/personal/'
    | '/transactions/'
    | '/groups/$id/recurring'
    | '/groups/$id/settings'
    | '/personal/category-budgets/$catId'
    | '/contacts/$id/'
    | '/groups/$id/'
    | '/personal/category-budgets/'
    | '/groups/$id/recurring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/contacts/new'
    | '/personal/budget-limit'
    | '/personal/categories'
    | '/personal/default-period'
    | '/personal/hide-ledgers'
    | '/personal/reports'
    | '/personal/settings'
    | '/transactions/$id'
    | '/auth'
    | '/contacts'
    | '/notifications'
    | '/personal'
    | '/transactions'
    | '/groups/$id/settings'
    | '/personal/category-budgets/$catId'
    | '/contacts/$id'
    | '/groups/$id'
    | '/personal/category-budgets'
    | '/groups/$id/recurring'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/personal'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/new'
    | '/groups/$id'
    | '/personal/budget-limit'
    | '/personal/categories'
    | '/personal/default-period'
    | '/personal/hide-ledgers'
    | '/personal/reports'
    | '/personal/settings'
    | '/transactions/$id'
    | '/auth/'
    | '/contacts/'
    | '/notifications/'
    | '/personal/'
    | '/transactions/'
    | '/groups/$id/recurring'
    | '/groups/$id/settings'
    | '/personal/category-budgets/$catId'
    | '/contacts/$id/'
    | '/groups/$id/'
    | '/personal/category-budgets/'
    | '/groups/$id/recurring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PersonalRoute: typeof PersonalRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ContactsIdRoute: typeof ContactsIdRouteWithChildren
  ContactsNewRoute: typeof ContactsNewRoute
  GroupsIdRoute: typeof GroupsIdRouteWithChildren
  TransactionsIdRoute: typeof TransactionsIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/': {
      id: '/personal/'
      path: '/'
      fullPath: '/personal/'
      preLoaderRoute: typeof PersonalIndexRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/settings': {
      id: '/personal/settings'
      path: '/settings'
      fullPath: '/personal/settings'
      preLoaderRoute: typeof PersonalSettingsRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/personal/reports': {
      id: '/personal/reports'
      path: '/reports'
      fullPath: '/personal/reports'
      preLoaderRoute: typeof PersonalReportsRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/personal/hide-ledgers': {
      id: '/personal/hide-ledgers'
      path: '/hide-ledgers'
      fullPath: '/personal/hide-ledgers'
      preLoaderRoute: typeof PersonalHideLedgersRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/personal/default-period': {
      id: '/personal/default-period'
      path: '/default-period'
      fullPath: '/personal/default-period'
      preLoaderRoute: typeof PersonalDefaultPeriodRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/personal/categories': {
      id: '/personal/categories'
      path: '/categories'
      fullPath: '/personal/categories'
      preLoaderRoute: typeof PersonalCategoriesRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/personal/budget-limit': {
      id: '/personal/budget-limit'
      path: '/budget-limit'
      fullPath: '/personal/budget-limit'
      preLoaderRoute: typeof PersonalBudgetLimitRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/category-budgets/': {
      id: '/personal/category-budgets/'
      path: '/category-budgets'
      fullPath: '/personal/category-budgets/'
      preLoaderRoute: typeof PersonalCategoryBudgetsIndexRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/groups/$id/': {
      id: '/groups/$id/'
      path: '/'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof GroupsIdIndexRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/contacts/$id/': {
      id: '/contacts/$id/'
      path: '/'
      fullPath: '/contacts/$id/'
      preLoaderRoute: typeof ContactsIdIndexRouteImport
      parentRoute: typeof ContactsIdRoute
    }
    '/personal/category-budgets/$catId': {
      id: '/personal/category-budgets/$catId'
      path: '/category-budgets/$catId'
      fullPath: '/personal/category-budgets/$catId'
      preLoaderRoute: typeof PersonalCategoryBudgetsCatIdRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/groups/$id/settings': {
      id: '/groups/$id/settings'
      path: '/settings'
      fullPath: '/groups/$id/settings'
      preLoaderRoute: typeof GroupsIdSettingsRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/groups/$id/recurring': {
      id: '/groups/$id/recurring'
      path: '/recurring'
      fullPath: '/groups/$id/recurring'
      preLoaderRoute: typeof GroupsIdRecurringRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/groups/$id/recurring/': {
      id: '/groups/$id/recurring/'
      path: '/'
      fullPath: '/groups/$id/recurring/'
      preLoaderRoute: typeof GroupsIdRecurringIndexRouteImport
      parentRoute: typeof GroupsIdRecurringRoute
    }
  }
}

interface NotificationsRouteChildren {
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface PersonalRouteChildren {
  PersonalBudgetLimitRoute: typeof PersonalBudgetLimitRoute
  PersonalCategoriesRoute: typeof PersonalCategoriesRoute
  PersonalDefaultPeriodRoute: typeof PersonalDefaultPeriodRoute
  PersonalHideLedgersRoute: typeof PersonalHideLedgersRoute
  PersonalReportsRoute: typeof PersonalReportsRoute
  PersonalSettingsRoute: typeof PersonalSettingsRoute
  PersonalIndexRoute: typeof PersonalIndexRoute
  PersonalCategoryBudgetsCatIdRoute: typeof PersonalCategoryBudgetsCatIdRoute
  PersonalCategoryBudgetsIndexRoute: typeof PersonalCategoryBudgetsIndexRoute
}

const PersonalRouteChildren: PersonalRouteChildren = {
  PersonalBudgetLimitRoute: PersonalBudgetLimitRoute,
  PersonalCategoriesRoute: PersonalCategoriesRoute,
  PersonalDefaultPeriodRoute: PersonalDefaultPeriodRoute,
  PersonalHideLedgersRoute: PersonalHideLedgersRoute,
  PersonalReportsRoute: PersonalReportsRoute,
  PersonalSettingsRoute: PersonalSettingsRoute,
  PersonalIndexRoute: PersonalIndexRoute,
  PersonalCategoryBudgetsCatIdRoute: PersonalCategoryBudgetsCatIdRoute,
  PersonalCategoryBudgetsIndexRoute: PersonalCategoryBudgetsIndexRoute,
}

const PersonalRouteWithChildren = PersonalRoute._addFileChildren(
  PersonalRouteChildren,
)

interface ContactsIdRouteChildren {
  ContactsIdIndexRoute: typeof ContactsIdIndexRoute
}

const ContactsIdRouteChildren: ContactsIdRouteChildren = {
  ContactsIdIndexRoute: ContactsIdIndexRoute,
}

const ContactsIdRouteWithChildren = ContactsIdRoute._addFileChildren(
  ContactsIdRouteChildren,
)

interface GroupsIdRecurringRouteChildren {
  GroupsIdRecurringIndexRoute: typeof GroupsIdRecurringIndexRoute
}

const GroupsIdRecurringRouteChildren: GroupsIdRecurringRouteChildren = {
  GroupsIdRecurringIndexRoute: GroupsIdRecurringIndexRoute,
}

const GroupsIdRecurringRouteWithChildren =
  GroupsIdRecurringRoute._addFileChildren(GroupsIdRecurringRouteChildren)

interface GroupsIdRouteChildren {
  GroupsIdRecurringRoute: typeof GroupsIdRecurringRouteWithChildren
  GroupsIdSettingsRoute: typeof GroupsIdSettingsRoute
  GroupsIdIndexRoute: typeof GroupsIdIndexRoute
}

const GroupsIdRouteChildren: GroupsIdRouteChildren = {
  GroupsIdRecurringRoute: GroupsIdRecurringRouteWithChildren,
  GroupsIdSettingsRoute: GroupsIdSettingsRoute,
  GroupsIdIndexRoute: GroupsIdIndexRoute,
}

const GroupsIdRouteWithChildren = GroupsIdRoute._addFileChildren(
  GroupsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  PersonalRoute: PersonalRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ContactsIdRoute: ContactsIdRouteWithChildren,
  ContactsNewRoute: ContactsNewRoute,
  GroupsIdRoute: GroupsIdRouteWithChildren,
  TransactionsIdRoute: TransactionsIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
